server:
  port: 8099

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microServices
 
 
        
  config:
    import: optional:configserver:http://localhost:8089
  application:
    name: RATINGSERVICE    
#  profiles:
#    active:prod
    
#eureka:
#
#  instance:
#    hostname: localhost
#    ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#  
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
    
okta:
  oauth2:
    issuer: https://dev-57450036.okta.com/oauth2/default 
    audience: api://default
